baseURL = "https://felipecesar.dev/"
languageCode = "pt-br"
title = "Felipe Cesar - Desenvolvedor Front-End"
theme = "yinyang"
DefaultContentLanguage = "pt-br"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = false
    style = "bw"
    tabWidth = 2

[author]
  name = "Felipe"
  homepage = "https://twitter.com/felipecesr"

[languages]
  [languages.pt-br]
    contentDir = "content/pt-br"
    languageName = "Portuguese"
    weight = 1
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 2

[params]
mainSections = ["posts"]
headTitle = "Felipe Cesar"
disqus = "felipecesar" # disqus account name
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=GTM-5TG84ZB"></script>'
extraCSSFiles = ["css/syntax.css"]
[[params.socials]]
name = "Github"
link = "https://github.com/felipecesr"
[[params.socials]]
name = "LinkedIn"
link = "https://www.linkedin.com/in/felipecesr/"
[[params.socials]]
name = "Twitter"
link = "https://twitter.com/felipecesr"
