[[plugins]]
package = "netlify-plugin-cache-nextjs"

[[plugins]]
package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    dataDir = "site/_data"

    [[plugins.inputs.feeds]]
      name = "hawksworx"
      url = "https://felipecesar.dev/feed.json"
      ttl = 120
    [[plugins.inputs.feeds]]
      name = "netlify"
      url = "https://felipecesar.dev/index.xml"
      ttl = 86400
