backend:
  name: github
  branch: master
  repo: felipecesr/felipecesar.dev
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
collections:
  - label: "Blog in Portuguese"
    name: "portuguese_posts"
    label_singular: "Blog Post"
    folder: "content/pt-br/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "default",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Blog in English"
    name: "english_posts"
    label_singular: "Blog Post"
    folder: "content/en/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "default",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }